### ISSUE TITLE
[16:46:31 ERROR]: [dough: protection] An Error occured while registering the Protection Module: "HuskTowns" v1.8

### ISSUE THREAD

**Issue by AdhityaXD1604** [WiIIiam278/HuskTowns#135]
[16:46:31 INFO]: [dough: protection] Loaded Protection Module "WorldGuard v7.0.7+216b061"
[16:46:31 ERROR]: [dough: protection] An Error occured while registering the Protection Module: "HuskTowns" v1.8
java.lang.NoClassDefFoundError: me/william278/husktowns/HuskTownsAPI
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.modules.HuskTownsProtectionModule.load(HuskTownsProtectionModule.java:30) ~[Slimefun.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(ProtectionManager.java:141) ~[Slimefun.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(ProtectionManager.java:133) ~[Slimefun.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.loadModuleImplementations(ProtectionManager.java:93) ~[Slimefun.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.<init>(ProtectionManager.java:65) ~[Slimefun.jar:?]
        at io.github.thebusybiscuit.slimefun4.integrations.IntegrationsManager.onServerStart(IntegrationsManager.java:140) ~[Slimefun.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.william278.husktowns.HuskTownsAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 14 more

**Comment by WiIIiam278** [comment]
Already fixed in https://github.com/baked-libs/dough/pull/187
The plugin implementing dough need to update the version/commit of dough they target. Report this to their support quoting dough PR 187.
