### ISSUE TITLE
[Feature request] Add support for custom language files

### ISSUE THREAD

**Issue by fabianmakila** [WiIIiam278/HuskTowns#215]
Currently only the supported languages are allowed in the configuration. However for clarity, we'd like to use our own file instead of using en-gb for the translations. If you try to change the locale to for example `fi-fi` you get this error on startup:

```
Error occurred while enabling HuskTowns v2.2 (Is it up to date?)
java.lang.NullPointerException: Input stream cannot be null!
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at net.william278.husktowns.libraries.boostedyaml.YamlDocument.reload(YamlDocument.java:246) ~[HuskTowns-2.2.jar:?]
        at net.william278.husktowns.libraries.boostedyaml.YamlDocument.reload(YamlDocument.java:222) ~[HuskTowns-2.2.jar:?]
        at net.william278.husktowns.libraries.boostedyaml.YamlDocument.<init>(YamlDocument.java:91) ~[HuskTowns-2.2.jar:?]
        at net.william278.husktowns.libraries.boostedyaml.YamlDocument.create(YamlDocument.java:773) ~[HuskTowns-2.2.jar:?]
        at net.william278.husktowns.libraries.boostedyaml.YamlDocument.create(YamlDocument.java:792) ~[HuskTowns-2.2.jar:?]
        at net.william278.husktowns.libraries.annotaml.YamlObjectMap.parse(YamlObjectMap.java:70) ~[HuskTowns-2.2.jar:?]
        at net.william278.husktowns.libraries.annotaml.Annotaml.create(Annotaml.java:146) ~[HuskTowns-2.2.jar:?]
        at net.william278.husktowns.HuskTowns.loadConfig(HuskTowns.java:305) ~[HuskTowns-2.2.jar:?]
        at net.william278.husktowns.BukkitHuskTowns.onEnable(BukkitHuskTowns.java:106) ~[HuskTowns-2.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-492]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-492]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-492]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-492]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-492]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-492]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-492]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-492]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-492]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

Many other plugins already support this type of behavior and would make the translation of the plugin more straightforward.

**Comment by WiIIiam278** [comment]
You can just modify en-gb.yml — it’s just the file name which has to match
a valid “default” file

**Comment by fabianmakila** [comment]
Is there a reason this limit exists? Since you can create a Locale object for any language tag as long as it is a valid tag.

If however you plan on keeping this limitation, I think the startup error should at least be made more user friendly instead of the current NPE.

**Comment by WiIIiam278** [comment]
the way it works is it looks up the list of embedded resource files and finds it by the string locale tag. Ig the error could be made more clear on startup

**Comment by WiIIiam278** [comment]
Since this is how all my plugins work I think I'm gonna close this -- don't really want to introduce inconsistency. Simply put: Use the `language` setting to pick one of the default locales, and customize from there (including translating it to your own language if you wish). If you'd like to submit those locales to become a default, by all means feel free to PR :)
