### ISSUE TITLE
IllegalStateException on player join

### ISSUE THREAD

**Issue by fabianmakila** [WiIIiam278/HuskTowns#216]
After updating from 2.1 to 2.2 we are getting this error each time a player joins the game:

```
[HuskTowns] Plugin HuskTowns v2.2 generated an exception while executing task 1328
java.lang.IllegalStateException: User preferences not found for FabianAdrian
        at net.william278.husktowns.advancement.AdvancementTracker.lambda$checkAdvancements$0(AdvancementTracker.java:41) ~[HuskTowns-2.2.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.william278.husktowns.advancement.AdvancementTracker.checkAdvancements(AdvancementTracker.java:41) ~[HuskTowns-2.2.jar:?]
        at net.william278.husktowns.listener.EventListener.lambda$onPlayerJoin$1(EventListener.java:86) ~[HuskTowns-2.2.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.william278.husktowns.listener.EventListener.lambda$onPlayerJoin$2(EventListener.java:86) ~[HuskTowns-2.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-492]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-492]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Version information:**
Husktowns: `2.2`
Platform: `git-Paper-492 (MC: 1.19.4)`

**Comment by WiIIiam278** [comment]
Fixed in https://github.com/WiIIiam278/HuskTowns/commit/90593bb9cd2cce311f326dbb24df2bdddaffae1b
