### ISSUE TITLE
Column size too small

### ISSUE THREAD

**Issue by Mateget** [WiIIiam278/HuskTowns#240]
Hi I had this issue :

Failed to create claim world in table
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'world_environment' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931) ~[mysql-connector-java-5.1.49.jar:5.1.49] {}
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[mysql-connector-java-5.1.49.jar:5.1.49] {}
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.49.jar:5.1.49] {}

I suggest to improve the size of thie column for future users 

Quick Fix :

ALTER TABLE husktowns_claim_worlds MODIFY world_environment VARCHAR(32) NOT NULL;

**Comment by WiIIiam278** [comment]
Okay -- but I'm a bit confused? What environment is it failing to generate for?

```
CUSTOM - 6 chars
NORMAL - 6 chars
NETHER - 6 chars
THE_END - 7 chars
```

16 should be enough? Unless you're doing something wacky :) I'd like to know

**Comment by WiIIiam278** [comment]
Closed in https://github.com/WiIIiam278/HuskTowns/commit/5b2eb6e805783d4910fe9368005813382ca60221
