### ISSUE TITLE
Duplicate key in log timestamps causes critical failure to load towns

### ISSUE THREAD

**Issue by pacificminer** [WiIIiam278/HuskTowns#298]
Towns unable load on latest version 2.5.1. Has happened once causing about 200 towns not to load.

```[10:28:20] [Craft Scheduler Thread - 19 - HuskTowns/ERROR]: [HuskTowns] Failed to fetch list of towns from table
net.william278.husktowns.libraries.gson.JsonSyntaxException: duplicate key: 2023-07-30T00:29:19.829517550Z
	at net.william278.husktowns.libraries.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:189) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.Gson.fromJson(Gson.java:1227) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.Gson.fromJson(Gson.java:1137) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.Gson.fromJson(Gson.java:1047) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.libraries.gson.Gson.fromJson(Gson.java:982) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.database.MySqlDatabase.getAllTowns(MySqlDatabase.java:359) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.HuskTowns.loadTowns(HuskTowns.java:260) ~[HuskTowns-2.5.1.jar:?]
	at net.william278.husktowns.HuskTowns.lambda$loadData$6(HuskTowns.java:224) ~[HuskTowns-2.5.1.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by WiIIiam278** [comment]
Fixed in #300
