### ISSUE TITLE
Clickable rule flags not editable; console error

### ISSUE THREAD

**Issue by entonentoron** [WiIIiam278/HuskTowns#311]
I am getting the following error whenever a player tries to edit rule flags via `/t rules` in the click menu:

```
[14:26:12 WARN]: [HuskTowns] Plugin HuskTowns v2.5 generated an exception while executing task 88
java.lang.UnsupportedOperationException: null
        at java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.util.ImmutableCollections$AbstractImmutableMap.replace(ImmutableCollections.java:1077) ~[?:?]
        at net.william278.husktowns.claim.Rules.setFlag(Rules.java:79) ~[husktowns-2.5.jar:?]
        at net.william278.husktowns.manager.TownsManager.lambda$setFlagRule$88(TownsManager.java:837) ~[husktowns-2.5.jar:?]
        at net.william278.husktowns.manager.Manager.lambda$memberEditTown$1(Manager.java:87) ~[husktowns-2.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-132]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by entonentoron** [comment]
https://youtu.be/_N6OYKkr4lg
