### ISSUE TITLE
WorldGuard hook broken

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskTowns#465]
[18:56:08] [Server thread/ERROR]: Error occurred while enabling HuskTowns v3.0.4 (Is it up to date?)
java.lang.IllegalStateException: New flags cannot be registered at this time
at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.register(SimpleFlagRegistry.java:60) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at net.william278.husktowns.hook.WorldGuardHook.onEnable(WorldGuardHook.java:40) ~[HuskTowns-3.0.4.jar:?]
at net.william278.husktowns.hook.Hook.enable(Hook.java:45) ~[HuskTowns-3.0.4.jar:?]
at net.william278.husktowns.hook.WorldGuardHook.<init>(WorldGuardHook.java:34) ~[HuskTowns-3.0.4.jar:?]
at net.william278.husktowns.hook.BukkitWorldGuardHook.<init>(BukkitWorldGuardHook.java:38) ~[HuskTowns-3.0.4.jar:?]
at net.william278.husktowns.BukkitHuskTowns.onEnable(BukkitHuskTowns.java:191) ~[HuskTowns-3.0.4.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:672) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:56:08] [Server thread/INFO]: [HuskTowns] Disabling HuskTowns v3.0.4

**Comment by WiIIiam278** [comment]
Closed by #468
