### ISSUE TITLE
Database error when disbanding town (tested on SQLite, might need to test on mysql as well?)

### ISSUE THREAD

**Issue by Ekmot276** [WiIIiam278/HuskTowns#73]
While **/town disband [confirm]** shows, that your town has been successfully deleted it looks like there is an internal error with the database handling of towns. Even after the user got the confirmation in chat, that his town has been deleted he still can't create a new one (_Error: You're already a member of a town_).

The user also can not leave his town using **/town leave** which gives no feedback in chat and throws this console error:

`[17:41:56 INFO]: Ekmot276 issued server command: /town leave
[17:41:56 WARN]: [HuskTowns] Plugin HuskTowns v1.6.1 generated an exception while executing task 86
java.lang.NullPointerException: Cannot invoke "me.william278.husktowns.town.Town.getName()" because "<local2>" is null
        at me.william278.husktowns.data.DataManager.lambda$leaveTown$5(DataManager.java:709) ~[HuskTowns-1.6.1.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-388]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-388]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]`
        
Running the **/town disband [confirm]** command again tells the player, that (_Error: Only the mayor can disband a town_).

----------
**Update**

Steps to reproduce on a standalone paper-server (build 388) and HuskTowns version 1.6.2-dev:

1. /town create TEST
2. /town claim
3. Leave Server
4. Restart Server
5. Join Server
6. /town disband
7. /town disband confirm
❌ 8. /town create TEST (_Error: You're already a member of a town_)

[log](https://pastebin.com/BWQU30y3)

**Comment by WiIIiam278** [comment]
Seems to be an issue with SQLite foreign constraints failing...possibly a driver issue?

**Comment by Ekmot276** [comment]
----------
**Update**

Steps to reproduce on a standalone paper-server (build 388) and HuskTowns version 1.6.2-dev:

1. /town create TEST
2. /town claim
3. Leave Server
4. Restart Server
5. Join Server
6. /town disband
7. /town disband confirm
❌ 8. /town create TEST (_Error: You're already a member of a town_)

[log](https://pastebin.com/BWQU30y3)
