### ISSUE TITLE
Exception when updating dynmap on first player join 

### ISSUE THREAD

**Issue by justaureus** [WiIIiam278/HuskTowns#99]
Sometimes rebooting a server running both HuskTowns and Dynmap causes exceptions on first player join as seen below:

```
[22:06:09 INFO]: [HuskTowns] Loading claim data into cache...
[22:06:09 WARN]: [HuskTowns] An exception occurred updating the Dynmap:null
[22:06:09 WARN]: me.william278.husktowns.cache.Cache$CacheNotLoadedException: Exception attempting to access unloaded Player Data cache (current state: UPDATING)
[22:06:09 WARN]:        at HuskTowns-1.7.jar//me.william278.husktowns.cache.PlayerCache.getPlayerUsername(PlayerCache.java:127)
[22:06:09 WARN]:        at HuskTowns-1.7.jar//me.william278.husktowns.integrations.map.Map.getClaimInfoWindow(Map.java:50)
[22:06:09 WARN]:        at HuskTowns-1.7.jar//me.william278.husktowns.integrations.map.DynMap.addMarker(DynMap.java:101)
[22:06:09 WARN]:        at HuskTowns-1.7.jar//me.william278.husktowns.cache.ClaimCache.add(ClaimCache.java:96)
[22:06:09 WARN]:        at HuskTowns-1.7.jar//me.william278.husktowns.data.DataManager.lambda$updateClaimedChunkCache$49(DataManager.java:3047)
[22:06:09 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:06:09 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:06:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:06:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:06:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:06:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:06:09 INFO]: [HuskTowns] Claim data caching complete (took 0 secs)
```

**Possible steps to reproduce exception:**
- Restart server which has configured Dynmap
- Join server as the first player to do so since restart
- Observe console

**Other notes:**
Original user to report this had Dynmap saving map data to MySQL.  If this is a map cache issue, perhaps the SQL data and cache data are conflicting?

**Comment by WiIIiam278** [comment]
This should no longer be the case as 2.0 has a new Dynmap integration
